name: deploy-mkdocs site

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-gen-files mdx_truly_sane_lists
      - name: Copy Readme
        run: |
          cp README.md notes/
      - name: Remove notes prefix from README links.
        run: |
          sed -ire "s;./notes/;;g" notes/README.md
      - run: mkdocs gh-deploy --force
